name: fb_auth
description: A Web, Mobile Firebase Auth Plugin
version: 1.0.2
author: Rody Davis <rody.davis.jr@gmail.com>
homepage: https://github.com/AppleEducate/fb_auth
issue_tracker: https://github.com/AppleEducate/plugins/issues
maintainer: Rody Davis (@AppleEducate)

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase: ^6.0.0
  firebase_auth: ^0.14.0+5
  bloc: ^1.0.0
  flutter_bloc: ^1.0.0
  http: ^0.12.0+2
  path_provider: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
